baseurl = "http://innovation-force.github.io/hipaa_docs/"
languageCode = "en-us"
title = "HIPAA Compliance Documents"
SectionPagesMenu = "main"
Copyright = "All rights reserved - 2016"
canonifyurls = true

[params]
   hideHUGOSupport = true

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Administrative Safeguards"
    weight = 1
    url = "/administrative_safeguards/"
  [[menu.main]]
    name = "Physical Safeguards"
    weight = 2
    url = "/physical_safeguards/"
  [[menu.main]]
    name = "Organizational Requirements"
    weight = 3
    url = "/organizational_requirements/"
