baseurl = "http://innovation-force.github.io/hipaa_docs/"
languageCode = "en-us"
title = "HIPAA Compliance Docs for Innovation Force"
SectionPagesMenu = "main"
Copyright = "All rights reserved - 2016"
DisqusShortname = "hipaaguidelines"
canonifyurls = true
paginate = 50

[params]
   hideHUGOSupport = true
   cover = "images/photo.jpg"
   githubName = "innovation-force"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Administrative Safeguards"
    weight = 1
    url = "/administrative_safeguards/"
  [[menu.main]]
    name = "Physical Safeguards"
    weight = 2
    url = "/physical_safeguards/"
  [[menu.main]]
    name = "Organizational Requirements"
    weight = 3
    url = "/organizational_requirements/"
  [[menu.main]]
    name = "Policies and Procedure Requirements"
    weight = 4
    url = "/policies_and_procedure_requirements/"
  [[menu.main]]
    name = "Hitech Act and Omnibus Rule"
    weight = 5
    url = "/hitech_and_omnibus_rule/"
  [[menu.main]]
    name = "About"
    weight = 6
    url = "/about/"
